# SQL Server service for development
version: "3.8"
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${DB_PASSWORD}
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql
    restart: unless-stopped
  db-init:
    image: mcr.microsoft.com/mssql/server:2022-latest
    network_mode: service:sqlserver
    environment:
      - DB_HOST=localhost
      - DB_USER=sa
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./init-db:/init-scripts
    command: bash /init-scripts/init-db.sh
    depends_on:
      - sqlserver
volumes:
  sqlserverdata:
