FROM mcr.microsoft.com/dotnet/sdk:9.0 AS migrate
WORKDIR /app

RUN dotnet tool install --global dotnet-ef
ENV PATH="$PATH:/root/.dotnet/tools"

COPY *.csproj ./
RUN dotnet restore

COPY . ./
COPY ./.env .env

ENTRYPOINT ["dotnet", "ef", "database", "update"]